- name: Setup Full Hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install GlusterFS release
  yum:
    name: centos-release-gluster40
    state: latest

- name: Config yum address
  shell: "sed -i 's/mirror.centos.org/{{ centos_yum_mirror }}/g' /etc/yum.repos.d/*"

- name: Install GlusterFS server
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libsemanage-python
    - glusterfs-server

- name: Enable glusterd service
  systemd:
    name: glusterd
    state: started
    enabled: yes